analyzer:
  errors:
    use_full_hex_values_for_flutter_colors: ignore
    avoid_print: ignore
    deprecated_member_use: ignore
    non_constant_identifier_names: ignore
    constant_identifier_names: ignore
   
include: package:flutter_lints/flutter.yaml

linter:
 
  rules:

